martyjs/marty

docs/css/docs.css

The default font used in docs is PT Serif, which I doubt many people have installed on their machine, so I'd added some alternatives in the CSS (Cambria and Georgia, 1st is from Win 7> I believe, the other is available on other systems I think). Otherwise the default serif font is used and that's Times New Roman for most people, which doesn't look good here IMO. I know, a minor thing, but will help me thinks ;)
PT Serif could be used as web font using for example Google Fonts, but there are many cons to that solution.

Additional fonts in the docs body

---

docs/_api/constants/index.md

The createConstants(obj) example was passing in an array, and it could be confusing.

Fix the docs so that the constants API example works

---

docs/_guides/stores/fetching-data.md

This sentence contains the typo : 
It also goes **againt** Flux's unidirectional data flow

Fixing typo

---

lib/stateSources/http.js

Related issue: https://github.com/jhollingworth/marty/issues/99

Fix for `isJson` when no "Content-Type" header

---

lib/diagnostics.js
lib/store.js

Making sure we always go through the Diagnostics object. Also added an extra check there that console exists, just in case someone on IE8 sets enabled to true.

Avoiding direct calls to console functions for IE8 happiness.

---

lib/stateSources/http.js

I just started trying to use Marty and my responses for a JSON request weren't coming back with a body. I tracked it down to `res.headers.map` being undefined. I'm not sure where `res.headers.map` coming from, but I certainly can't find it in the [isomorphic fetch](https://github.com/matthew-andrews/node-fetch/blob/master/lib/headers.js) library that Marty uses. Meanwhile, that fetch library does have a simple `get` method on headers.
Am I missing something here or is this a bug? It did fix my application.

Use res.headers.get for isJson

---

docs/_guides/stores/fetching-data.md

Set a fake JSON endpoint that would actually return something. [json placeholder](http://jsonplaceholder.typicode.com/) seems to work well for this. There are a good few use cases to test it with. :)

Use a fake JSON endpoint for the examples

---

lib/actionCreators.js
lib/fetch.js
lib/logger.js
lib/mixins/stateMixin.js
lib/store.js
lib/when.js
logger.js
test/actionCreatorsSpec.js
test/aliasesSpec.js
test/lib/stubbedLogger.js
test/stateMixinSpec.js
test/storeFetchTest.js
test/storeSpec.js
test/whenSpec.js

People have been finding it hard to diagnose where errors come from
because the promises would swallow them. I've added some logging around
places where Marty calls into user code, namely:
- `Store#handleAction`: We log the store, action handler, error and action
- `StateMixin#getState`: We log the view and error
- `when`: We log the fetch, store and error
- `ActionCreator`: We log the action type, action, action creator and error
Resolves #127

Improve error logging

---

docs/_guides/state-mixin/index.md

because if not the mixin makes little sense -- isn't it a hash containing a single key called `users`?

I'm hoping this is correct

---

HISTORY.md
karma.conf.js
package.json

Replaced `reactify` for `babelify` as Babel now supports JSX transforms too and will help with an ES6 transition.

Replaced reactify for babelify as Babel now supports JSX transforms

---

lib/stateSources/http.js
test/stateSources/httpStateSourceSpec.js

When the request body is a FormData object, Fetch automatically assigns the Content-Type header to "multipart/form-data; boundary={UNIQUE BOUNDARY TOKEN}". If Content-Type is already set, Fetch will not overwrite it. Thus, to support the multipart/form-data content-type, Marty should not automatically set the Content-Type to "application/json" when the request body is a FormData object.

Don't auto set content-type if using FormData

---

bower.json

Superagent seems to be unused. I found no references to it in any of the source, and it isn't even listed in package.json.

removed superagent from bower dependencies

---

package.json

Set `react`'s `peerDependency` to `>=0.13.0-rc2` as `>=0.12.0` wouldn't load it. Also set the right version for `marty`.

Set react's peerDendency to work with the RC

---

docs/_api/state-sources/http.md
lib/stateSource/inbuilt/http.js
test/browser/lib/mockServer.js
test/browser/stateSources/httpStateSourceSpec.js

* Add dataType option which behaves the same as in [$.ajax](http://api.jquery.com/jquery.ajax/). Fixes #161 
* Add contentType option that makes it easier to specify content type

Support dataType and contentType

---

bower.json
docs/_api/state-sources/cookie.md
docs/_guides/state-sources/cookie.md
lib/classes.js
lib/stateSource/createStateSourceClass.js
lib/stateSource/inbuilt/cookie.js
package.json
test/browser/stateSources/cookieStateSourceSpec.js

Adds a cookie state source which allows you to get/set/expire cookies. Will be useful for isomorphisim
```js
var UserCookies = Marty.createStateSource({
type: 'cookie',
login: function (user) {
this.set(user.id, true)
},
logout: function(id) {
this.expire(id);
}
isLoggedIn: function (id) {
return !!this.get(id);
}
});
```

Add CookieStateSource

---

docs/_api/stores/index.md
karma.conf.js
lib/actionPayload.js
lib/dispatcher.js
lib/store/store.js
test/browser/storeSpec.js

Stores change listeners will only be notified once for each action dispatched. This is so we don't unnecessarily cause components to re-render (As [discussed on the flux panel](https://www.youtube.com/watch?v=LTj4O7WJJ98&list=PLb0IAmt7-GS1cbw4qonlQztYV1TAW0sCr#t=473))

Batch store updates

---

docs/_guides/queries/index.md

Typographical fixes to queries guide in docs

---

lib/createContainer/createContainer.js

Standalone version is not executed by mistake of dependency.

fix path of dependent module

---

docs/_api/stores/index.md

I presume this is a hangover from the update to 0.9, and that the pattern I've used is the correct one. If I'm wrong let me know!

Stores API documentation fix (`UserAPI` -> `UserQueries`)

---

lib/createContainer/createContainer.js

Did not listen to propchanges (componentWillReceiveProps).
default for done was using an fat-arrow function. Accessing this in fat-arrow will bind it to the initial component.
The call later to done with .call(config, ..) did nothing because it was already bound.

container props and default done

---

lib/create.js
lib/createContainer/createContainer.js
lib/utils/getClassName.js
test/browser/containerSpec.js

Always ensure the `Container`'s name is getting the `InnerComponent`'s name.
Classical React components will get `displayName` [set through the jsx transformer](https://facebook.github.io/react/docs/component-specs.html#displayname) ([babel does it as well](https://babeljs.io/docs/usage/jsx/)).
Modern React components don't seem to get that treatment and `displayName` remains unset unless you explicitly set it.
```js
class MyComponent extends React.Component {}
typeof MyComponent.displayName === 'undefined' // => true
```
My first guess is to use [the constructor's property `name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name), however [IE doesn't support it yet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objec …

Always ensure the Container's name is getting the InnerComponent's name

---

dist/node/lib/create.js
dist/node/lib/registry.js
dist/node/lib/utils/getClassName.js
lib/create.js
lib/registry.js
lib/utils/getClassName.js
test/browser/registerSpec.js

Make sure ES6 registerables (like `Store`s, `StateSource`s and `ActionCreator`s) get their `id` to default to their class name.
[ref](https://gitter.im/jhollingworth/marty?at=5512b9e2a61b930e5dbca11a)
[manual test to showcase the issue](https://gist.github.com/dariocravero/c4442ad42412a43ec1ff)

Make sure ES6 registerables have their ids

---

lib/createContainer/createContainer.js

I'm creating a component that uses createContainer for fetching data from a store. The fetch is dependent on the props I pass in (e.g. date). This change will make sure that prop-dependent fetches will re-execute when props change.

Update state when receiving new props

---

docs/_guides/action-creators/handling-errors.md
docs/_guides/action-creators/index.md
docs/_guides/fetching-state/index.md
docs/_guides/flux/index.md
docs/_guides/queries/index.md
docs/_guides/state-sources/index.md
docs/_guides/stores/immutable-data-collections.md
docs/_guides/stores/index.md

Current docs just attempt to use a ES6 classs directly (not an instance). This doesn't work. Instances need to be obtained by using Marty.register

Docs: All ES6 classes need to be registered with Marty before using

---

docs/_guides/containers/index.md

Just swapped the syntax to actually be classic.

:memo: Tiny fix for classic container example

---

package.json

webpack's default resolve order for the main file in `package.json` is `webpack` > `browser` > ... > `main`. This means that webpack users will try to include `./marty.js`, which then includes the ES6 sources rather than the built ones, which means I then need to run everything through a transpiler for my build again.
Fixes #226

Use Node distribution in webpack

---

lib/createContainer/createContainer.js

For #249 
This also fixes a bug with `componentWillReceiveProps` where the base implementation would be overwritten by the configured one. I didn't explicitly add a test for this, but the existing test fails with thew new code without the change to `RESERVED_FUNCTIONS`.

Generate lifecycle methods at container creation

---

lib/createContainer/createContainer.js

Just came across a scenario where a store update caused the container to try and call setState when it was no longer mounted. This PR ensures setState is not called from onStoreChanged unless the container is currently mounted.

Do not setState in container unless component is mounted

---

docs/_guides/isomorphism/index.md

It looks like lib/renderToString.js expects `type` and `props` properties on the options object, not `component` and `props`

Fixing incorrect API example in Isomorphic docs

---

lib/stateSource/inbuilt/http/hooks/parseJSON.js

For #268 
I don't know how to write a test for this. The current tests fail against Chrome 43, but pass with this patch.

Work around not being able to set res.body

---

docs/_guides/fetching-state/index.md
docs/_guides/queries/index.md

The then/catch pattern used previously will also catch errors in listeners to the RECEIVE_USER action. This leads to weird things like exceptions in component rendering triggered by a successful user receive to be swallowed.

:memo: Better pattern for query error handling

---

lib/createContainer/createContainer.js
lib/createContainer/getFetchResult.js
test/browser/containerSpec.js

When there are pending fetches, we pass all done fetches into the
pending handler giving you the opportunity to provide default values.
Resolves #300

Pass finished fetch results into `pending`

---

http/hooks/throwOnError.js
lib/stateSource/inbuilt/http/hooks/throwOnError.js
lib/stateSource/inbuilt/http/index.js
test/browser/stateSources/httpStateSourceSpec.js

For martyjs/marty#308
The other changes to the test were due to some sloppiness with response codes that previously got through because we weren't rejecting on remote failures. Also, Sinon's fake server doesn't seem to work with native fetch (because it replaces XHR, which is only used by the polyfill), so need to match what's on the mock server as well.
I think the right thing to do is to just call into https://github.com/mzabriskie/axios instead of having this code in Marty, but it's probably best to have the old behavior back for the time being.

Add back old "reject on failure" behavior for HTTP

---

docs/_api/state-sources/http.md

This caused me some grief yesterday as I was wondering why it seemed like I could only have 1 hook added at a time. Stepping into addHook made it obvious why that was the case, since they are indexed by the undocumented 'id' property. Might save someone else some time if this is explicit in the docs.

Documented the fact that a hook requires an 'id' property if you plan on using multiple hooks.

---

package.json

I noticed that in the current version of firefox (v37), a fetch's response object did not have the .ok property, as it looks like the fetch polyfill is out of date. Updating the version of isomorphic-fetch resolves that.

Updated isomorphic-fetch dependency

---

lib/stateSource/inbuilt/http/index.js

The Fetch spec has normalization for some methods: https://fetch.spec.whatwg.org/#concept-method-normalize, but this doesn't include `PATCH`, which against sufficiently strict webservers must be specified as uppercase.

HTTP methods should be upper case

---

docs/_api/containers/index.md
docs/_api/stores/index.md

Explicitly document `Store#clear`
Fix markdown inside `Store#fetch` options table (Jekyll doesn't support Markdown there)
Use ES6-style spread syntax to note list of Stores in `Store#waitFor`
Explicitly document additional supported `createContainer` options.
Fixes #342

Improve docs a bit

---

docs/_guides/fetching-state/index.md

The first example on that guide is a little misleading because the `userAPI` should not be dispatching anything, which means nothing gets updated. This causes the call to `locally` return undefined, resulting in a "Not Found" error. May as well go with the less misleading `userQueries`.

:memo: Make an example more sensible

---

README.md
marty.d.ts
package.json

Thanks for taking a look at this PR! I've been using Marty with TypeScript for a little while and had to write out my own type definition for it. This file was originally based on `0.9`, but I updated it according to the change log and my application to `0.10`. It's possible there's still some parts missing.
Now, for some caveats of this. Currently the third-party definition system for TypeScript is fragmented with most people trying to publish to and consume a centralised repository. I'm currently working on the next version of TSD which will solve this issue at its core. For now, people will need to know (as mentioned in the README) that this definition requires React and Flux. If you wish to avoid this, you can change the types to `any` but that will ignore type information around …

Add a TypeScript definition

---

README.md
marty.js
package.json

I'm really sorry to be making this change, but I have some old stuff that I haven't had the chance to migrate off Marty yet, because my next update is going to be with GraphQL/Relay instead, and I haven't had time to do that yet.

:arrow_up: Update for React v0.14 (sorry!)
