martyjs/marty

- docs/_guides/flux/index.md
There is a further missing '('
> Added missing '('

- docs/index.md
> :microscope: Remove rogue `to` then reword, punctuate and capitalise

- docs/_guides/flux/index.md
Loving these docs @jhollingworth
> Fix Flux code examples 

- docs/_guides/state-mixin/index.md
- docs/_guides/stores/fetching-data.md
- docs/_guides/stores/immutable-data-collections.md
Amazing docs for such a new project! I hope this helps. I checked the other PRs and didn't see much (or any) overlap. I can rebase and resend this if these changes conflict with others.
Thanks again!
> :memo: Fixed minor typos in docs

- lib/stateSources/http.js
> Add patch method to HttpStateSource

- karma.conf.js
- lib/stateSources/http.js
> Hotfix for fetch on Chrome Canary

- karma.conf.js
- lib/container.js
- lib/utils/classId.js
- lib/utils/humanStrings.js
> Improve warning messages

- karma.conf.js
- lib/store/fetch.js
- lib/store/fetchResult.js
- test/browser/storeFetchSpec.js
If a fetch depends on other fetches then trigger Store#hasChanged when all of those dependencies are done/failed. Resolves #113.
> Update store when dependencies update

- http/hooks/includeCredentials.js
- lib/stateSource/inbuilt/http/hooks/includeCredentials.js
- lib/stateSource/inbuilt/http/index.js
> Set request credentials to 'same-origin'

- docs/_guides/isomorphism/index.md
> Made link to expressjs.com go to the Express site

- HISTORY.md
- lib/createContainer/createContainer.js
- test/browser/containerSpec.js
- test/browser/registerSpec.js
> Container improvements

- HISTORY.md
- lib/store/fetch.js
- test/browser/storeFetchSpec.js
> Dont catch errors in locally or remotely

- HISTORY.md
- lib/createContainer/createContainer.js
- lib/createContainer/getFetchResult.js
- test/browser/containerSpec.js
> Use latest props when container is updating fetches

- HISTORY.md
- lib/createContainer/createContainer.js
- test/browser/containerSpec.js
> Container observer bug and container lifestyle hooks. 

- lib/store/when.js
- test/browser/whenSpec.js
> Remove when try-catch

- docs/_guides/isomorphism/index.md
This improves the renderToString example in the docs so that the error case is handled and provides a response rather than a "hanging" server.
> Improves the renderToString example

- dist/node/lib/renderToString.js
- lib/renderToString.js
- test/server/renderToStringSpec.js
> Return the individual html parts.

- docs/_api/containers/index.md
- docs/_api/inject-app/index.md
- docs/_data/api_section_order.yml
These are the features added by https://github.com/martyjs/marty-lib/pull/20 for https://github.com/martyjs/marty/issues/338 and https://github.com/martyjs/marty-lib/issues/17.
> :memo: Document new container features

- docs/_api/test-utils/index.md
> Changed wrong name

- docs/_guides/dispatcher/index.md
I guess there was a missing word there :)
> Added missing word to dispatcher guide
